### ISSUE TITLE
Alternate `aeon` packages for conda

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [conda-forge/aeon-feedstock#2]
There are separate packages under [auto](https://anaconda.org/auto/aeon) and [bioconda](https://bioconda.github.io/recipes/aeon/README.html) with the `aeon` name.
 
The first package used to hold the PyPi name prior to releasing it to us. Would either of these cause issues with installing the package using `conda`?

**Comment by ocefpaf** [comment]
Only if folks mix channels. If they are using a single channel, as it is recommended, that is not a problem.

**Comment by MatthewMiddlehurst** [comment]
Thanks for answering, if its fine on the recommended method thats good enough really.
